name: Gerar Dados

on:
  schedule: # executar a cada 12 horas
    - cron: "0 2 * * 1-5"
  workflow_dispatch:

jobs:
  build:
    name: Trabalhos para atualizar dados
    runs-on: ubuntu-latest
    steps:
      # Animação de Serpente
      - uses: platane/snk@master
        id: cobra-gif
        with:
          github_user_nome: Hellanlins
          svg_out_pát: dist/github-contribution-grid-snake.com

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: main
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
